<?php

return [
    'CL' => [
        'XV' => [
            'Arica',
            'Camarones',
            'Putre',
            'General Lagos'
        ],
        'I' => [
            'Iquique',
            'Alto Hospicio',
            'Pozo Almonte',
            'Camiña',
            'Colchane',
            'Huara',
            'Pica'
        ],
        'II' => [
            'Antofagasta',
            'Mejillones',
            'Sierra Gorda',
            'Taltal',
            'Calama',
            'Ollagüe',
            'San Pedro de Atacama',
            'Tocopilla',
            'María Elena'
        ],
        'III' => [
            'Copiapó',
            'Caldera',
            'Tierra Amarilla',
            'Chañaral',
            'Diego de Almagro',
            'Vallenar',
            'Alto del Carmen',
            'Freirina',
            'Huasco'
        ],
        'IV' => [
            'La Serena',
            'Coquimbo',
            'Andacollo',
            'La Higuera',
            'Paihuano',
            'Vicuña',
            'Illapel',
            'Canela',
            'Los Vilos',
            'Salamanca',
            'Ovalle',
            'Combarbalá',
            'Monte Patria',
            'Punitaqui',
            'Río Hurtado'
        ],
        'V' => [
            _x('Valparaíso', ' Valparaiso', 'ry-wc-city-select'),
            _x('Casablanca', ' Valparaiso', 'ry-wc-city-select'),
            _x('Concón', ' Valparaiso', 'ry-wc-city-select'),
            _x('Juan Fernández', ' Valparaiso', 'ry-wc-city-select'),
            _x('Puchuncaví', ' Valparaiso', 'ry-wc-city-select'),
            _x('Quintero', ' Valparaiso', 'ry-wc-city-select'),
            _x('Viña del Mar', ' Valparaiso', 'ry-wc-city-select'),
            _x('Isla de Pascua', ' Valparaiso', 'ry-wc-city-select'),
            _x('Los Andes', ' Valparaiso', 'ry-wc-city-select'),
            _x('Calle Larga', ' Valparaiso', 'ry-wc-city-select'),
            _x('Rinconada', ' Valparaiso', 'ry-wc-city-select'),
            _x('San Esteban', ' Valparaiso', 'ry-wc-city-select'),
            _x('La Ligua', ' Valparaiso', 'ry-wc-city-select'),
            _x('Cabildo', ' Valparaiso', 'ry-wc-city-select'),
            _x('Papudo', ' Valparaiso', 'ry-wc-city-select'),
            _x('Petorca', ' Valparaiso', 'ry-wc-city-select'),
            _x('Zapallar', ' Valparaiso', 'ry-wc-city-select'),
            _x('Quillota', ' Valparaiso', 'ry-wc-city-select'),
            _x('La Calera', ' Valparaiso', 'ry-wc-city-select'),
            _x('Hijuelas', ' Valparaiso', 'ry-wc-city-select'),
            _x('La Cruz', ' Valparaiso', 'ry-wc-city-select'),
            _x('Nogales', ' Valparaiso', 'ry-wc-city-select'),
            _x('San Antonio', ' Valparaiso', 'ry-wc-city-select'),
            _x('Algarrobo', ' Valparaiso', 'ry-wc-city-select'),
            _x('Cartagena', ' Valparaiso', 'ry-wc-city-select'),
            _x('El Quisco', ' Valparaiso', 'ry-wc-city-select'),
            _x('El Tabo', ' Valparaiso', 'ry-wc-city-select'),
            _x('Santo Domingo', ' Valparaiso', 'ry-wc-city-select'),
            _x('San Felipe', ' Valparaiso', 'ry-wc-city-select'),
            _x('Catemu', ' Valparaiso', 'ry-wc-city-select'),
            _x('Llaillay', ' Valparaiso', 'ry-wc-city-select'),
            _x('Panquehue', ' Valparaiso', 'ry-wc-city-select'),
            _x('Putaendo', ' Valparaiso', 'ry-wc-city-select'),
            _x('Santa María', ' Valparaiso', 'ry-wc-city-select'),
            _x('Quilpué', ' Valparaiso', 'ry-wc-city-select'),
            _x('Limache', ' Valparaiso', 'ry-wc-city-select'),
            _x('Olmué', ' Valparaiso', 'ry-wc-city-select'),
            _x('Villa Alemana', ' Valparaiso', 'ry-wc-city-select'),
        ],
        'VI' => [
            'Rancagua',
            'Codegua',
            'Coinco',
            'Coltauco',
            'Doñihue',
            'Graneros',
            'Las Cabras',
            'Machalí',
            'Malloa',
            'Mostazal',
            'Olivar',
            'Peumo',
            'Pichidegua',
            'Quinta de Tilcoco',
            'Rengo',
            'Requínoa',
            'San Vicente',
            'Pichilemu',
            'La Estrella',
            'Litueche',
            'Marchihue',
            'Navidad',
            'Paredones',
            'San Fernando',
            'Chépica',
            'Chimbarongo',
            'Lolol',
            'Nancagua',
            'Palmilla',
            'Peralillo',
            'Placilla',
            'Pumanque',
            'Santa Cruz'
        ],
        'VII' => [
            'Talca',
            'Constitución',
            'Curepto',
            'Empedrado',
            'Maule',
            'Pelarco',
            'Pencahue',
            'Río Claro',
            'San Clemente',
            'San Rafael',
            'Cauquenes',
            'Chanco',
            'Pelluhue',
            'Curicó',
            'Hualañé',
            'Licantén',
            'Molina',
            'Rauco',
            'Romeral',
            'Sagrada Familia',
            'Teno',
            'Vichuquén',
            'Linares',
            'Colbún',
            'Longaví',
            'Parral',
            'Retiro',
            'San Javier',
            'Villa Alegre',
            'Yerbas Buenas'
        ],
        'VIII' => [
            'Concepción',
            'Coronel',
            'Chiguayante',
            'Florida',
            'Hualqui',
            'Lota',
            'Penco',
            'San Pedro de La Paz',
            'Santa Juana',
            'Talcahuano',
            'Tomé',
            'Hualpén',
            'Lebu',
            'Arauco',
            'Cañete',
            'Contulmo',
            'Curanilahue',
            'Los Álamos',
            'Tirúa',
            'Los Ángeles',
            'Antuco',
            'Cabrero',
            'Laja',
            'Mulchén',
            'Nacimiento',
            'Negrete',
            'Quilaco',
            'Quilleco',
            'San Rosendo',
            'Santa Bárbara',
            'Tucapel',
            'Yumbel',
            'Alto Biobío',
        ],
        /**
         * Nueva Región de Ñuble!
         **/
        'XVI' => [
            'Chillán',
            'Bulnes',
            'Cobquecura',
            'Coelemu',
            'Coihueco',
            'Chillán Viejo',
            'El Carmen',
            'Ninhue',
            'Ñiquén',
            'Pemuco',
            'Pinto',
            'Portezuelo',
            'Quillón',
            'Quirihue',
            'Ránquil',
            'San Carlos',
            'San Fabián',
            'San Ignacio',
            'San Nicolás',
            'Treguaco',
            'Yungay'
        ],
        'IX' => [
            'Temuco',
            'Carahue',
            'Cunco',
            'Curarrehue',
            'Freire',
            'Galvarino',
            'Gorbea',
            'Lautaro',
            'Loncoche',
            'Melipeuco',
            'Nueva Imperial',
            'Padre Las Casas',
            'Perquenco',
            'Pitrufquén',
            'Pucón',
            'Saavedra',
            'Teodoro Schmidt',
            'Toltén',
            'Vilcún',
            'Villarrica',
            'Cholchol',
            'Angol',
            'Collipulli',
            'Curacautín',
            'Ercilla',
            'Lonquimay',
            'Los Sauces',
            'Lumaco',
            'Purén',
            'Renaico',
            'Traiguén',
            'Victoria'
        ],
        'XIV' => [
            'Valdivia',
            'Corral',
            'Lanco',
            'Los Lagos',
            'Máfil',
            'Mariquina',
            'Paillaco',
            'Panguipulli',
            'La Unión',
            'Futrono',
            'Lago Ranco',
            'Río Bueno'
        ],
        'X' => [
            'Puerto Montt',
            'Calbuco',
            'Cochamó',
            'Fresia',
            'Frutillar',
            'Los Muermos',
            'Llanquihue',
            'Maullín',
            'Puerto Varas',
            'Castro',
            'Ancud',
            'Chonchi',
            'Curaco de Vélez',
            'Dalcahue',
            'Puqueldón',
            'Queilén',
            'Quellón',
            'Quemchi',
            'Quinchao',
            'Osorno',
            'Puerto Octay',
            'Purranque',
            'Puyehue',
            'Río Negro',
            'San Juan de la Costa',
            'San Pablo',
            'Chaitén',
            'Futaleufú',
            'Hualaihué',
            'Palena'
        ],
        'XI' => [
            'Coyhaique',
            'Lago Verde',
            'Aysén',
            'Cisnes',
            'Guaitecas',
            'Cochrane',
            'O\'Higgins',
            'Tortel',
            'Chile Chico',
            'Río Ibáñez'
        ],
        'XII' => [
            'Punta Arenas',
            'Laguna Blanca',
            'Río Verde',
            'San Gregorio',
            'Cabo de Hornos',
            'Antártica',
            'Porvenir',
            'Primavera',
            'Timaukel',
            'Natales',
            'Torres del Paine'
        ],
        'RM' => [
            _x('Santiago', 'Metropolitana', 'ry-wc-city-select'),
            _x('Cerrillos', 'Metropolitana', 'ry-wc-city-select'),
            _x('Cerro Navia', 'Metropolitana', 'ry-wc-city-select'),
            _x('Conchalí', 'Metropolitana', 'ry-wc-city-select'),
            _x('El Bosque', 'Metropolitana', 'ry-wc-city-select'),
            _x('Estación Central', 'Metropolitana', 'ry-wc-city-select'),
            _x('Huechuraba', 'Metropolitana', 'ry-wc-city-select'),
            _x('Independencia', 'Metropolitana', 'ry-wc-city-select'),
            _x('La Cisterna', 'Metropolitana', 'ry-wc-city-select'),
            _x('La Florida', 'Metropolitana', 'ry-wc-city-select'),
            _x('La Granja', 'Metropolitana', 'ry-wc-city-select'),
            _x('La Pintana', 'Metropolitana', 'ry-wc-city-select'),
            _x('La Reina', 'Metropolitana', 'ry-wc-city-select'),
            _x('Las Condes', 'Metropolitana', 'ry-wc-city-select'),
            _x('Lo Barnechea', 'Metropolitana', 'ry-wc-city-select'),
            _x('Lo Espejo', 'Metropolitana', 'ry-wc-city-select'),
            _x('Lo Prado', 'Metropolitana', 'ry-wc-city-select'),
            _x('Macul', 'Metropolitana', 'ry-wc-city-select'),
            _x('Maipú', 'Metropolitana', 'ry-wc-city-select'),
            _x('Ñuñoa', 'Metropolitana', 'ry-wc-city-select'),
            _x('Pedro Aguirre Cerda', 'Metropolitana', 'ry-wc-city-select'),
            _x('Peñalolén', 'Metropolitana', 'ry-wc-city-select'),
            _x('Providencia', 'Metropolitana', 'ry-wc-city-select'),
            _x('Pudahuel', 'Metropolitana', 'ry-wc-city-select'),
            _x('Quilicura', 'Metropolitana', 'ry-wc-city-select'),
            _x('Quinta Normal', 'Metropolitana', 'ry-wc-city-select'),
            _x('Recoleta', 'Metropolitana', 'ry-wc-city-select'),
            _x('Renca', 'Metropolitana', 'ry-wc-city-select'),
            _x('San Joaquín', 'Metropolitana', 'ry-wc-city-select'),
            _x('San Miguel', 'Metropolitana', 'ry-wc-city-select'),
            _x('San Ramón', 'Metropolitana', 'ry-wc-city-select'),
            _x('Vitacura', 'Metropolitana', 'ry-wc-city-select'),
            _x('Puente Alto', 'Metropolitana', 'ry-wc-city-select'),
            _x('Pirque', 'Metropolitana', 'ry-wc-city-select'),
            _x('San José de Maipo', 'Metropolitana', 'ry-wc-city-select'),
            _x('Colina', 'Metropolitana', 'ry-wc-city-select'),
            _x('Lampa', 'Metropolitana', 'ry-wc-city-select'),
            _x('Til Til', 'Metropolitana', 'ry-wc-city-select'),
            _x('San Bernardo', 'Metropolitana', 'ry-wc-city-select'),
            _x('Buin', 'Metropolitana', 'ry-wc-city-select'),
            _x('Calera de Tango', 'Metropolitana', 'ry-wc-city-select'),
            _x('Paine', 'Metropolitana', 'ry-wc-city-select'),
            _x('Melipilla', 'Metropolitana', 'ry-wc-city-select'),
            _x('Alhué', 'Metropolitana', 'ry-wc-city-select'),
            _x('Curacaví', 'Metropolitana', 'ry-wc-city-select'),
            _x('María Pinto', 'Metropolitana', 'ry-wc-city-select'),
            _x('San Pedro', 'Metropolitana', 'ry-wc-city-select'),
            _x('Talagante', 'Metropolitana', 'ry-wc-city-select'),
            _x('El Monte', 'Metropolitana', 'ry-wc-city-select'),
            _x('Isla de Maipo', 'Metropolitana', 'ry-wc-city-select'),
            _x('Padre Hurtado', 'Metropolitana', 'ry-wc-city-select'),
            _x('Peñaflor', 'Metropolitana', 'ry-wc-city-select'),
        ]
    ]
];